wandb_version: 1

task:
  desc: null
  value: inference
_wandb:
  desc: null
  value:
    python_version: 3.11.1
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1722504641.036572
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.1
      5: 0.16.3
      6: 4.37.2
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
